language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL=""
      script: make test
      env:
        - MATRIX_EVAL="brew update && brew install ctags"
    - os: linux
      dist: trusty
      env: COMPILER_NAME
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - lcov
            - cmake
            - libboost-all-dev
      env:
        - MATRIX_EVAL="pip install --user cpp-coveralls && sCC=gcc-7 && CXX=g++-7"
      script: make COVERAGE=On test
      after_success:
        - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - clang-5.0
            - cmake
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      script: make test

before_install:
    - eval "${MATRIX_EVAL}"
    - $CXX --version
