language: cpp
script: make test
matrix:
  include:
    - os: linux
      dist: trusty
      env: COMPILER_NAME
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - libc++-dev
            - clang-5.0
            - cmake
            - libboost-all-dev
      env:
        - MATRIX_EVAL='CC=clang-5.0 && CXX="clang++-5.0 -stdlib=libc++"'

before_install:
    - eval "${MATRIX_EVAL}"
    - $CXX --version
