language: cpp
jobs:
  include:

    - os: linux
      dist: trusty
      env: COMPILER_NAME
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - lcov
            - cmake
            - libboost-all-dev
      env:
        - NAME="GCC v7.0 on Linux"
      script: make COVERAGE=On test
      before_install:
        - CC=gcc-7
        - CXX=g++-7
        - pip install --user cpp-coveralls
      after_success:
        - coveralls --exclude lib --exclude test --gcov-options '\-lp'

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - clang-5.0
            - cmake
            - libboost-all-dev
      env:
        - NAME="LLVM Clang v5.0 on Linux"
      script: make test
      before_install:
        - CC=clagn-5.0
        - CXX=clang++-5.0

    - os: osx
      osx_image: xcode9.3beta
      script: make test
      env:
        - NAME="OS X"
      before_install:
        - brew update
        - brew install ctags
        - brew install gcc || true
        - brew link --overwrite gcc
